language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: true
addons:
  apt:
    packages:
    - libgconf-2-4
install:
  - npm ci
node_js:
  - '12'
script:
  - npm run lint
  - npm run build
  - travis_retry npm test
# after_success:
#   - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
